### ISSUE TITLE
Doesn't work on iOS/ipad

### ISSUE THREAD

**Issue by acomito** [jacobbuck/react-beforeunload#15]
Just checked my web app on ipad and I don't think it's working.

Looks like it may require some extra work?

https://stackoverflow.com/questions/3239834/window-onbeforeunload-not-working-on-the-ipad

**Comment by tomatillodesign** [comment]
Same issue for me; also not working on iOS / iPhone. Desktop version works great!

**Comment by jacobbuck** [comment]
Closing this as iOS Safari doesn't support the `beforeunload` event and there's no suitable workaround for it.
