### ISSUE TITLE
can we disable the dialogue box

### ISSUE THREAD

**Issue by irfanDC** [jacobbuck/react-beforeunload#16]
We dont need to show the dialogue box but just need to call a function on leave.  

<Beforeunload onBeforeunload={this.leavingSession} />

**Comment by jacobbuck** [comment]
Yes, the dialog only shows if you call `preventDefault()` on the event or the event handler returns a string.

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Comment by irfanDC** [comment]
worked. thanks
