### ISSUE TITLE
Question about the component approach of BeforeUnload

### ISSUE THREAD

**Issue by YoannBuzenet** [jacobbuck/react-beforeunload#17]
Hello,

and thank you for this package ! I plan to use the hook approach to display a message.

However, I wanted to ask : what is the purpose of the component approach ? Why use it when there are hooks that are more powerful ?

Thanks
Yoann

**Comment by jacobbuck** [comment]
Hi there, glad you find it useful 😄 

Originally react-beforeunload was written as a component (before hooks were introduced.) Now the component uses the hook under the hood and provides the same functionality as the hook and I've only kept it around for backwards-compatibility. 

The component is still useful for applications that use class components or developers that prefer it over hooks, but for newer applications I recommend using the hook.
