### ISSUE TITLE
Callback for cancel & Leave button

### ISSUE THREAD

**Issue by rohitkothiya** [jacobbuck/react-beforeunload#18]
How can i call custom function for cancel and leave button ?

**Comment by jacobbuck** [comment]
See #7

**Comment by rohitkothiya** [comment]
HI, @jacobbuck So what  is the use of this package for beforunload event if i have to make custom function ?

**Comment by jacobbuck** [comment]
This package provides a simple and consistent way to listen to the `beforeunload` event with React and doesn't provide any  additional features or logic.
