### ISSUE TITLE
Beforeunload.render(): A valid React element (or null) must be returned.

### ISSUE THREAD

**Issue by DrUNE** [jacobbuck/react-beforeunload#2]
When using component without children elements (`<Beforeunload onBeforeunload={this.handleBeforeunload}/>`) render method return undefined, which is not permitted in React.
To fix the problem render method should looks like this:
```
render () {
    return this.props.children || null
}
```

**Comment by jacobbuck** [comment]
Fixed in 1.0.3 😄
