### ISSUE TITLE
How to differentiate between relaod and close in side callback function?

### ISSUE THREAD

**Issue by haarshjani** [jacobbuck/react-beforeunload#23]

**Comment by jacobbuck** [comment]
[You can't](https://stackoverflow.com/questions/11453741/javascript-beforeunload-detect-refresh-versus-close#14893469)

**Comment by haarshjani** [comment]
hi jacobe,
               I noticed that if we use event.preventDefault() then while reload the alert give reload and cancel and leave.is there any improvement you can do in that?

thank you in advance.

**Comment by jacobbuck** [comment]
Unfortunately not, as the behaviour of the [`beforeunload`](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) event is implemented by browsers according to the HTML specification.
