### ISSUE TITLE
Custom messages do not work anymore it seems.

### ISSUE THREAD

**Issue by DoubleHelixX** [jacobbuck/react-beforeunload#25]
Updated versions of chrome seem to have implemented a new security feature.

**Comment by jacobbuck** [comment]
As mentioned in this repo's [README.md](https://github.com/jacobbuck/react-beforeunload#custom-message-support):

> ⚠️ Some browsers used to display the returned string in the confirmation dialog, enabling the event handler to display a custom message to the user. However, this is deprecated and no longer supported in most browsers.
