### ISSUE TITLE
Typechecks incompatible with docs

### ISSUE THREAD

**Issue by JuanGaray93** [jacobbuck/react-beforeunload#26]
I just installed this package and tried to use it with a custom message. This was the result:

![image](https://user-images.githubusercontent.com/31663056/130251868-792ea9ab-e8dd-409b-9e2d-f04baf5ce907.png)

the type of the callback should include `()  => string | undefined;`. I also noticed that the callback doesn't accept the event value as shown in the docs.

**Comment by jacobbuck** [comment]
This module doesn't use Typescript or export type definitions, so I'm unsure why your IDE is showing you these errors.

**Comment by JuanGaray93** [comment]
Ah, it looks like DefinitelyTyped is providing the typing. I'll report it there.
