### ISSUE TITLE
block confirm function before unload

### ISSUE THREAD

**Issue by isekaimaou1109** [jacobbuck/react-beforeunload#28]
i want to use confirm to detect user opinion about save current time video but when it's not working as i expected. 
![image](https://user-images.githubusercontent.com/49366277/144241778-13f08602-139b-40a4-946a-0076e99c4efa.png)
the screenshot above is the error message and the below is my code hope someone help me T-T and thanks
```javascript
useBeforeunload((event) => {
    if(videoRef.current.currentTime <= videoRef.current.duration - 10) {
      var answer = confirm('<message>')
      if (answer) {
        /* something */
      } else {
        event.preventDefault();
      }
    }
  });
```

**Comment by jacobbuck** [comment]
> The HTML specification states that calls to [`window.alert()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/alert), [`window.confirm()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm), and [`window.prompt()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) methods may be ignored during this event. See the [HTML specification](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#user-prompts) for more details.

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
