### ISSUE TITLE
This is not working for Firefox.

### ISSUE THREAD

**Issue by ngdevc** [jacobbuck/react-beforeunload#30]

**Comment by sdancer75** [comment]
I am not sure what is happening with this package. I used the same code as yours at the demo but it doesn't work or it works intermittently. Component `Beforeunload` never worked. I tested this with chrome v110 and firefox  v110. Any ideas?


```
import logo from "./logo.svg";
import "./App.css";
import { useBeforeunload } from "react-beforeunload";

function App() {
  useBeforeunload((event) => {
    event.preventDefault();
    console.log("beforeunload happened!");
  });

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a className="App-link" href="https://reactjs.org" target="_blank" rel="noopener noreferrer">
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```
my react-dom and scripts in my case, are newer than yours. Maybe there is a break in newer versions?

```
    "react": "^18.2.0",
    "react-beforeunload": "^2.5.3",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
```

**Comment by sdancer75** [comment]
Ok, It seems that there is a serious delay before this event is actually set from React. 

You have to wait about 5-10 seconds before this finally works after the page load even a very lite one like the initial react script page.
