### ISSUE TITLE
beforeunload doesn't handle event of back button?

### ISSUE THREAD

**Issue by Rongeegee** [jacobbuck/react-beforeunload#32]
Are you guys going to add this feature later?

**Comment by jacobbuck** [comment]
This is to do with back/forward cache: https://web.dev/bfcache/#only-add-beforeunload-listeners-conditionally

I've updated the [useBeforeunload hook](https://github.com/jacobbuck/react-beforeunload#usebeforeunload-hook-recommended) in v2.6.0 to support conditional listening, which addresses this issue. For example:

```js
  useBeforeunload((event) => {
    if (condition) {
      event.preventDefault();
    }
  });
```

should now be:

```js
  useBeforeunload(condition && ((event) => event.preventDefault()));
```

or:

```js
  useBeforeunload(condition ? (event) => event.preventDefault() : null);
```

Related: https://github.com/jacobbuck/react-beforeunload/issues/9#issuecomment-1111979391
