### ISSUE TITLE
Can't display default dialog without returning a string

### ISSUE THREAD

**Issue by otroboe** [jacobbuck/react-beforeunload#4]
Hello!

I'm trying to implement the hook, and I have to return a string (dummy because not used), to make it work.
I would expect that the first line (the one in your `README`), should work :)

```javascript
// Not working
useBeforeunload(event => event.preventDefault());
useBeforeunload();
useBeforeunload(() => {});

// Working
useBeforeunload(() => 'You wont see me');
```

My specs:
- Ubuntu `18.04`
- Chrome `Version 75.0.3770.80 (Official Build) (64-bit)`
- React `16.8.6`

Thank you!

**Comment by jacobbuck** [comment]
Hey! Thanks for the bug report. Good spotting. So it turns on Chrome doesn't support using `event.preventDefault()`, despite what the HTML specification states.

I've just published v2.0.1 which adds a workaround for Chrome so `preventDefault` will now work 😄
